# Working with multiple data sets

There are two data files that we'll be working with for this week's assignment.  They are described below.  Load those data files in with Pandas and then work to answering each of the questions below.

## npidata.csv

This file is basic information about every healthcare provider in the US.  It has one row for each NPI (National Provider Identifier).  It contains information such as the provider's name and address.


## cmsYYYY.csv

These are files about what kinds of procedures and patients providers in the US are serving under CMS programs, Medicare and Medicaid.  Each contains various statistics about providers over the course of a year.  There are three of these, for the years 2014, 2015, and 2016.  These files, however, don't contain information about the provider such as where the provider is located.

## Our Goals

For this assignment, we're going to want to compute some statistics based on the data in the **cms** files, but aggregate that data based on information in the **npidata** file.  As in last week's assignment, you'll need to store your answers in a variable called `answer` at the end of each step.

In [25]:
import pandas as pd

## Part 1

In this first step, we'll need to merge together all of the **cms** files into a single dataframe.  Be careful that these files might not be identical, so you'll have to look a little bit to figure out how to merge them.

As you are merging them, make sure that you retain information about which file (i.e. which year) the data came from.  Call that new columns `year`.

In your `answer` variable, provide a complete data frame that contains all of the rows and columns from the **cms** files, plus an additional column to store the year/file that particular row came from.

The assertion tests will give you a good idea as to if you're merging the files correctly.

In [26]:
cms2014 = pd.read_csv("/data/cms2014.csv")
cms2015 = pd.read_csv("/data/cms2015.csv")
cms2016 = pd.read_csv("/data/cms2016.csv")
cms2014.columns = cms2014.columns.str.lower()
cms2015.columns = cms2015.columns.str.lower()
cms2016.columns = cms2016.columns.str.lower()
cms2014.insert(0, "year", "")
cms2014['year'] = 2014
cms2015.insert(0, "year", "")
cms2015['year'] = 2015
cms2016.insert(0, "year", "")
cms2016['year'] = 2016
cms = pd.concat([cms2014, cms2015, cms2016])
answer = pd.concat([cms2014, cms2015, cms2016])

### SOLUTION

In [4]:
assert(answer.shape == (193862, 60))
assert(list(answer['year'].unique()) == [2014,2015,2016])
assert(set(answer.columns.str.lower()) == set(['year', 'nbr', 'npi', 'provider_type',
       'medicare_participation_indicator', 'number_of_hcpcs', 'total_services',
       'total_unique_benes', 'total_submitted_chrg_amt',
       'total_medicare_allowed_amt', 'total_medicare_payment_amt',
       'total_medicare_stnd_amt', 'drug_suppress_indicator',
       'number_of_drug_hcpcs', 'total_drug_services',
       'total_drug_unique_benes', 'total_drug_submitted_chrg_amt',
       'total_drug_medicare_allowed_amt', 'total_drug_medicare_payment_amt',
       'total_drug_medicare_stnd_amt', 'med_suppress_indicator',
       'number_of_med_hcpcs', 'total_med_services', 'total_med_unique_benes',
       'total_med_submitted_chrg_amt', 'total_med_medicare_allowed_amt',
       'total_med_medicare_payment_amt', 'total_med_medicare_stnd_amt',
       'beneficiary_average_age', 'beneficiary_age_less_65_count',
       'beneficiary_age_65_74_count', 'beneficiary_age_75_84_count',
       'beneficiary_age_greater_84_count', 'beneficiary_female_count',
       'beneficiary_male_count', 'beneficiary_race_white_count',
       'beneficiary_race_black_count', 'beneficiary_race_api_count',
       'beneficiary_race_hispanic_count', 'beneficiary_race_natind_count',
       'beneficiary_race_other_count', 'beneficiary_nondual_count',
       'beneficiary_dual_count', 'beneficiary_cc_afib_percent',
       'beneficiary_cc_alzrdsd_percent', 'beneficiary_cc_asthma_percent',
       'beneficiary_cc_cancer_percent', 'beneficiary_cc_chf_percent',
       'beneficiary_cc_ckd_percent', 'beneficiary_cc_copd_percent',
       'beneficiary_cc_depr_percent', 'beneficiary_cc_diab_percent',
       'beneficiary_cc_hyperl_percent', 'beneficiary_cc_hypert_percent',
       'beneficiary_cc_ihd_percent', 'beneficiary_cc_ost_percent',
       'beneficiary_cc_raoa_percent', 'beneficiary_cc_schiot_percent',
       'beneficiary_cc_strk_percent', 'beneficiary_average_risk_score']))

In [43]:
answer.head()

,year,nbr,npi,provider_type,medicare_participation_indicator,number_of_hcpcs,total_services,total_unique_benes,total_submitted_chrg_amt,total_medicare_allowed_amt,...,beneficiary_cc_depr_percent,beneficiary_cc_diab_percent,beneficiary_cc_hyperl_percent,beneficiary_cc_hypert_percent,beneficiary_cc_ihd_percent,beneficiary_cc_ost_percent,beneficiary_cc_raoa_percent,beneficiary_cc_schiot_percent,beneficiary_cc_strk_percent,beneficiary_average_risk_score
0,2014,1,1003000134,Pathology,Y,13,8643.0,4276,1357139.00,321641.88,...,12.0,20.0,53.0,57.0,28.0,9.0,37.0,1.0,3.0,1.0007
1,2014,19,1003001249,Physical Therapist,Y,4,1221.0,69,88686.28,34060.09,...,NaN,39.0,64.0,75.0,32.0,NaN,68.0,NaN,NaN,1.1912
2,2014,21,1003001322,Mass Immunization Roster Biller,Y,7,788.0,370,21640.24,21634.91,...,13.0,18.0,42.0,49.0,24.0,5.0,25.0,NaN,3.0,0.8019
3,2014,37,1003002486,Chiropractic,Y,2,142.0,22,7458.44,5037.51,...,NaN,NaN,59.0,59.0,NaN,0.0,64.0,0.0,0.0,0.7920
4,2014,73,1003005430,Clinical Psychologist,Y,3,130.0,11,20640.00,14968.22,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.9718

In [20]:
cms.head()

,year,nbr,npi,provider_type,medicare_participation_indicator,number_of_hcpcs,total_services,total_unique_benes,total_submitted_chrg_amt,total_medicare_allowed_amt,...,beneficiary_cc_depr_percent,beneficiary_cc_diab_percent,beneficiary_cc_hyperl_percent,beneficiary_cc_hypert_percent,beneficiary_cc_ihd_percent,beneficiary_cc_ost_percent,beneficiary_cc_raoa_percent,beneficiary_cc_schiot_percent,beneficiary_cc_strk_percent,beneficiary_average_risk_score
0,2014,1,1003000134,Pathology,Y,13,8643.0,4276,1357139.00,321641.88,...,12.0,20.0,53.0,57.0,28.0,9.0,37.0,1.0,3.0,1.0007
1,2014,19,1003001249,Physical Therapist,Y,4,1221.0,69,88686.28,34060.09,...,NaN,39.0,64.0,75.0,32.0,NaN,68.0,NaN,NaN,1.1912
2,2014,21,1003001322,Mass Immunization Roster Biller,Y,7,788.0,370,21640.24,21634.91,...,13.0,18.0,42.0,49.0,24.0,5.0,25.0,NaN,3.0,0.8019
3,2014,37,1003002486,Chiropractic,Y,2,142.0,22,7458.44,5037.51,...,NaN,NaN,59.0,59.0,NaN,0.0,64.0,0.0,0.0,0.7920
4,2014,73,1003005430,Clinical Psychologist,Y,3,130.0,11,20640.00,14968.22,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.9718

## Part 2

In this next part, we're going to join the **cms** data with the provider information in the **/data/npidata.csv** file.  In this join, we don't want to lose any records from the **cms** files, even if no matching provider exists in the **npidata** file.  However, we don't care about any providers from the **npidata** file that don't have records in the **cms** files.  Those providers can be ignored.

Join the data files together to create one unified data frame called `answer`.  This dataframe should have all the columns from both **cms** and **npidata** files, joined together using the `npi` column.  

Note that `npi` is unique in the **npidata** file.

In [29]:
npidata = pd.read_csv("/data/npidata.csv")
full = cms.merge(npidata, how='left', left_on = "npi", right_on = "NPI")
answer = cms.merge(npidata, how='left', left_on = "npi", right_on = "NPI")
### SOLUTION
answer.shape

(193862, 103)

<bound method NDFrame.head of             row         NPI  Entity Type Code  Replacement NPI  \
0            13  1205839354               1.0              NaN
1            15  1023011079               2.0              NaN
2            74  1932102969               1.0              NaN
3            88  1477556405               1.0              NaN
4            89  1386647311               1.0              NaN
...         ...         ...               ...              ...
251656  4363896  1821407230               1.0              NaN
251657  4363897  1225447667               2.0              NaN
251658  4363906  1841609278               2.0              NaN
251659  4363963  1790194132               2.0              NaN
251660  4363975  1003225442               NaN              NaN

       Employer Identification Number (EIN)  \
0                                       NaN
1                                 <UNAVAIL>
2                                       NaN
3                                       NaN
4                                       NaN
...                                     ...
251656                                  NaN
251657                            <UNAVAIL>
251658                            <UNAVAIL>
251659                            <UNAVAIL>
251660                                  NaN

       Provider Organization Name (Legal Business Name)  \
0                                                   NaN
1                      ADVANTAGE HOME HEALTH CARE, INC.
2                                                   NaN
3                                                   NaN
4                                                   NaN
...                                                 ...
251656                                              NaN
251657               DR. DOUGLAS J. COCHRAN D.D.S. P.C.
251658                            DOUBLE G LAND CO, LLC
251659                         CHESTERFIELD VILLAS, LLC
251660                                              NaN

       Provider Last Name (Legal Name) Provider First Name  \
0                            DIFILIPPO                EMIL
1                                  NaN                 NaN
2                               HELFER              TAMARA
3                          LINSENMEYER             CHARLES
4                               LASKEN                GARY
...                                ...                 ...
251656                          ECKERT                KALI
251657                             NaN                 NaN
251658                             NaN                 NaN
251659                             NaN                 NaN
251660                             NaN                 NaN

       Provider Middle Name Provider Name Prefix Text  ...  \
0                         A                       DR.  ...
1                       NaN                       NaN  ...
2                         G                       DR.  ...
3                         M                       DR.  ...
4                         W                       DR.  ...
...                     ...                       ...  ...
251656                  NaN                       NaN  ...
251657                  NaN                       NaN  ...
251658                  NaN                       NaN  ...
251659                  NaN                       NaN  ...
251660                  NaN                       NaN  ...

       Provider Business Practice Location Address Postal Code  \
0                                             6.33664e+08
1                                             6.04509e+08
2                                             6.18204e+08
3                                             6.33013e+08
4                                             6.16142e+08
...                                                   ...
251656                                        6.06115e+08
251657                                        6.41183e+08
251658                                        6.30176e+08
251659                                        6.30176e+08
251660                                                NaN

       Provider Business Practice Location Address Country Code (If outside U.S.)  \
0                                                      US
1                                                      US
2                                                      US
3                                                      US
4                                                      US
...                                                   ...
251656                                                 US
251657                                                 US
251658                                                 US
251659                                                 US
251660                                                NaN

       Provider Business Practice Location Address Telephone Number  \
0                                              6365615030
1                                              8154671905
2                                              2173661255
3                                              6369467050
4                                              3096925500
...                                                   ...
251656                                         3123376960
251657                                         8164362150
251658                                         3144342520
251659                                         6365329296
251660                                                NaN

        Provider Business Practice Location Address Fax Number  \
0                                            6.365615e+09
1                                            8.154676e+09
2                                            2.173666e+09
3                                            6.369463e+09
4                                            3.096926e+09
...                                                   ...
251656                                                NaN
251657                                       8.164362e+09
251658                                       3.144344e+09
251659                                       6.365321e+09
251660                                                NaN

       Provider Enumeration Date Last Update Date  \
0                     05/23/2005       05/06/2015
1                     05/23/2005       12/12/2014
2                     05/23/2005       01/24/2014
3                     05/23/2005       07/08/2007
4                     05/23/2005       05/19/2011
...                          ...              ...
251656                08/11/2014       08/11/2014
251657                08/11/2014       09/02/2014
251658                08/11/2014       08/11/2014
251659                08/11/2014       08/11/2014
251660                       NaN              NaN

       NPI Deactivation Reason Code NPI Deactivation Date  \
0                               NaN                   NaN
1                               NaN                   NaN
2                               NaN                   NaN
3                               NaN                   NaN
4                               NaN                   NaN
...                             ...                   ...
251656                          NaN                   NaN
251657                          NaN                   NaN
251658                          NaN                   NaN
251659                          NaN                   NaN
251660                          NaN                   NaN

       NPI Reactivation Date Provider Gender Code
0                        NaN                    M
1                        NaN                  NaN
2                        NaN                    F
3                        NaN                    M
4                        NaN                    M
...                      ...                  ...
251656                   NaN                    F
251657                   NaN                  NaN
251658                   NaN                  NaN
251659                   NaN                  NaN
251660                   NaN                  NaN

[251661 rows x 43 columns]>

In [28]:
import numpy
assert(answer.shape == (193862, 103))
assert(list(answer['Provider Business Mailing Address State Name'].unique()) == ['IL','MO',numpy.nan,'WY'])
assert(list(answer.groupby('Provider Business Mailing Address State Name').NPI.count()) == [111520, 53366, 4805])

## Part 3

If you did everything right above, you'll notice that grouping by a column with NaN in it will cause some rows to disappear from the aggregation test.  So, let's create a new column called `'State'` that has the same value as whatever is in the `'Provider Business Mailing Address State Name'` column or a value of `'XX'` if there is no state information.

Set `answer` to be your final data frame with the new `'State'` column added.

In [33]:
full['State'] = full['Provider Business Mailing Address State Name']
answer = full

### SOLUTION

In [34]:
full['Provider Business Mailing Address State Name']

0         IL
1         IL
2         MO
3         MO
4         IL
          ..
193857    IL
193858    IL
193859    MO
193860    IL
193861    MO
Name: Provider Business Mailing Address State Name, Length: 193862, dtype: object

In [35]:
assert(list(answer.groupby('State').npi.count()) == [111520, 53366, 4805, 24171])
assert(answer.shape == (193862, 104))

AssertionError:

## Part 4

Next, let's summarize the data by year and by State.  Create a pivot table that contains one row for each state and one column for each year.  Within the pivot table, put a sum of total services as the values.

Assign `answer` to be that resulting pivot table.  In the tests, I'm going to plot a bar chart of your pivot table.

In [ ]:
%matplotlib inline
answer = None

### SOLUTION

In [ ]:
assert(answer.shape == (4,3))
assert(answer.sum().sum() == 519185664.6999999)
assert(answer[2016].sum() == 176596933.80000004)
assert(answer.loc['WY'].sum() == 10892707.4)

In [ ]:
%matplotlib inline
answer.plot.bar()



---



## Submitting Your Work

In order to submit your work, you'll need to use the `git` command line program to **add** your homework file (this file) to your local repository, **commit** your changes to your local repository, and then **push** those changes up to github.com.  From there, I'll be able to **pull** the changes down and do my grading.  I'll provide some feedback, **commit** and **push** my comments back to you.  Next week, I'll show you how to **pull** down my comments.

To run through everything one last time and submit your work:
1. Use the `Kernel` -> `Restart Kernel and Run All Cells` menu option to run everything from top to bottom and stop here.
2. Follow the instruction on the prompt below to either ssave and submit your work, or continue working.

If anything fails along the way with this submission part of the process, let me know.  I'll help you troubleshoort.

---

In [1]:
a=input('''
Are you ready to submit your work?
1. Click the Save icon (or do Ctrl-S / Cmd-S)
2. Type "yes" or "no" below
3. Press Enter

''')

if a=='yes':
    !git pull
    !git add week14_assignment.ipynb
    !git commit -a -m "Submitting the week 14 programming assignment"
    !git push
else:
    print('''
    
OK. We can wait.
''')

Are you ready to submit your work?
1. Click the Save icon (or do Ctrl-S / Cmd-S)
2. Type "yes" or "no" below
3. Press Enter

OK. We can wait.